### ISSUE TITLE
テストコードを書こう

### ISSUE THREAD

**Issue by shiotomo** [onlinejanken/Jajanken#15]
## 内容

自分の作成したプログラムが正しく動作していることを保証するために、テストコードを書いてみましょう。  
今後開発を進める上で、バグの少ないプログラムを作ること手助けになります。

## 参考URL

https://mochajs.org/
https://dev.classmethod.jp/server-side/node-mocha/

## 備考

少しずつでいいのでバックエンドのプログラムにはテストコードを書きましょう。  
特に `src` のプログラムは単体テストが将来的に大事になってくると考えられます。

**Comment by shiotomo** [comment]
まずは、 #13のプログラムにテストコードを書いてみることをおすすめします。

**Comment by tokutatsu** [comment]
ありがとうございます。
参考のサイトを見ながらやってみます。

**Comment by tokutatsu** [comment]
テストコードはどこに置くのが良いでしょうか。

**Comment by tokutatsu** [comment]
#13 のテストを書いているのですが、ランダムなIDを生成するモジュールをテストをする時は、
``assert.equal('モジュールの関数,' '期待している値')``の``'期待している値'``のところをどのように書けばよいでしょうか。

**Comment by shiotomo** [comment]
- 生成するランダムなIDの長さは常に予測しているものか(8文字なら常に8文字で生成されるか)
- 生成するランダムなIDは常に英数字のみになっているか(正規表現でテストできそう)
この2つの項目をテストすればいいかもです。

assert.equalのテストはなくても良いと思います。
ここで行いたいのは正しいIDが生成されるかどうかなので、Validationのテストが通れば問題ないと思います。

**Comment by tokutatsu** [comment]
なるほどです、ありがとうございます。
テストは``.gitignore``に書いて管理対象から外したほうがいいですかね。

**Comment by shiotomo** [comment]
testは管理対象にしたほうがよいです。
その理由として、他の人がプログラムをリファクタリングする際テストコードを用いることで既存の機能が壊れていないか確認できるからです。
また、現在はこのプロジェクトに導入されていませんがCIを利用して開発を始めた場合、自動的にテストを実行することができるのでtestは管理対象にしましょう。

**Comment by tokutatsu** [comment]
そうなのですか、了解です。

**Comment by shiotomo** [comment]
テストコードを少しずつ書けているみたいなのでこのissueは閉じておきます。
