### ISSUE TITLE
ゲーム音を付ける

### ISSUE THREAD

**Issue by tokutatsu** [onlinejanken/Jajanken#150]
## 概要
ゲームのクリック音や、バックグラウンド音を付ける。
その際、トップ画面に音が出るという警告を付ける。
優先度は低い。

**Comment by oreotabetai** [comment]
ボタンをerror以外に追加した。
Choromで自動再生されないのはChoromの仕様である。

**Comment by oreotabetai** [comment]
他のページでBGMを開くとウインドウが増える問題がある。
