### ISSUE TITLE
titleの実装

### ISSUE THREAD

**Issue by oreotabetai** [onlinejanken/Jajanken#3]
## 概要

スタート画面のコードを載せる

**Comment by oreotabetai** [comment]
#5 内のtitle.html, title.js, title.cssに変更を加えてしまった

**Comment by tokutatsu** [comment]
wikiに主な作業の流れを書いておきました。

(https://github.com/onlinejanken/Jajanken/wiki/Git%E3%81%A7%E4%BD%9C%E6%A5%AD%E3%81%99%E3%82%8B%E9%9A%9B%E3%81%AE%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%81%A8%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AA%E4%BD%9C%E6%A5%AD%E3%81%AE%E6%B5%81%E3%82%8C)
