### ISSUE TITLE
controllerの実装

### ISSUE THREAD

**Issue by tokutatsu** [onlinejanken/Jajanken#4]
## 概要
controllerでのルーティング処理を実装する
とりあえずファイル分けはせずに一つのファイルに書いて良いです(後で分けるかも)
~~htmlファイルを返す処理を書いてあげてください~~
追記: htmlファイルからejsファイルに変更

## その他
test.jsが一応参考になるかと思います

**Comment by tokutatsu** [comment]
controller.jsを置いておいたのでそこに書いていきましょう。

**Comment by tokutatsu** [comment]
wikiに主な作業の流れを書いておきました。

(https://github.com/onlinejanken/Jajanken/wiki/Git%E3%81%A7%E4%BD%9C%E6%A5%AD%E3%81%99%E3%82%8B%E9%9A%9B%E3%81%AE%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%81%A8%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AA%E4%BD%9C%E6%A5%AD%E3%81%AE%E6%B5%81%E3%82%8C)

**Comment by git-Ktu** [comment]
追加するのってtitles,admins,participantsの3つでよかったですか？

**Comment by tokutatsu** [comment]
とりあえずそれで大丈夫です。

**Comment by tokutatsu** [comment]
ルーム待機画面へのルーティング設定をお願いします。
``/participants/wait/:roomId``のように指定してあげると、``req.param``オブジェクトの中で、パスに指定されたルート・パラメータの名前をそれぞれのキーとして設定されます。
参考URL
https://expressjs.com/ja/guide/routing.html
